steps:
# Run Tests 
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/shout:$COMMIT_SHA', '.']
# Run Integration Tests: 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '-d', '-p', '8080:8080', '-e', 'PORT=8080', 'gcr.io/$PROJECT_ID/shout:$COMMIT_SHA' , './run_test.sh']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/shout:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'shout'
    - '--image'
    - 'gcr.io/$PROJECT_ID/shout:$COMMIT_SHA'
    - '--region'
    - 'us-west1'
    - '--platform'
    - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/shout:$COMMIT_SHA'
